name: Pipeline

on:
  push:

env:
  DATABRICKS_HOST: https://adb-7984910318720673.13.azuredatabricks.net/

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps: 
      - name: Generate AAD Token
        run: |
          echo "DATABRICKS_TOKEN=$(curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
              https://login.microsoftonline.com/${{ secrets.AZURE_SERVICE_PRINCIPLE_TENANT_ID }}/oauth2/v2.0/token \
              -d 'client_id=${{ secrets.AZURE_SERVICE_PRINCIPLE_APPLICATION_ID }}' \
              -d 'grant_type=client_credentials' \
              -d 'scope=2ff814a6-3304-4ab8-85cb-cd0e6f879c1d%2F.default' \
              -d 'client_secret=${{ secrets.AZURE_SERVICE_PRINCIPLE_CLIENT_SECRET }}' |  jq -r  '.access_token')" >> $GITHUB_ENV

      - name: Run notebook
        uses: databricks/run-notebook@v0
        with: 
          local-notebook-path: notebook_1.py
          existing-cluster-id: 0719-081544-1g6epb5w
          git-commit: ${{ github.sha }}
            
          
          
    